import type { LearningPath } from '@/types/skill'

export const MOCK_LEARNING_PATHS: LearningPath[] = [
  {
    id: 'path-001',
    title: 'Start Learning AI from Zero',
    slug: 'start-learning-ai-from-zero',
    short_description: 'Go from complete beginner to confident AI user in under 10 hours with hands-on practice.',
    long_description: 'This path is for anyone who has heard about AI tools but does not know where to start. By the end, you will use AI tools confidently in your daily work.',
    status: 'published',
    tags: ['beginner', 'foundations'],
    source_urls: [],
    goal: 'Build foundational AI literacy and hands-on confidence.',
    who_its_for: 'Complete beginners — students, professionals, or anyone curious about AI tools.',
    required_skill_level: 'beginner',
    estimated_hours: 8,
    modules: [
      { module: 1, title: 'What Is AI and How Does It Work?', description: 'Understand LLMs and their limitations.', skills: ['prompt-engineering-basics'], tools: [], duration_hours: 1 },
      { module: 2, title: 'Your First AI Tool: ChatGPT', description: 'Hands-on with ChatGPT. Write effective prompts.', skills: ['prompt-engineering-basics'], tools: ['chatgpt'], duration_hours: 2 },
      { module: 3, title: 'The AI Tool Landscape', description: 'Explore Claude, Gemini, and Perplexity.', skills: ['ai-tool-selection'], tools: ['claude', 'gemini', 'perplexity'], duration_hours: 2 },
      { module: 4, title: 'AI Beyond Text', description: 'Images with DALL-E 3, voice with ElevenLabs.', skills: ['ai-image-midjourney'], tools: ['dall-e-3', 'elevenlabs'], duration_hours: 2 },
      { module: 5, title: 'Your First Real AI Project', description: 'Complete a small project with AI.', skills: ['write-system-prompts'], tools: ['chatgpt', 'claude'], duration_hours: 1 },
    ],
    practice_tasks: [
      'Write 5 prompts for the same task and compare results',
      'Generate an image with DALL-E 3 using progressively more specific prompts',
    ],
    mini_projects: [
      'Create a personal AI prompt library with 10 prompts you will actually use',
    ],
    completion_checklist: [
      'Understand what LLMs are and what they cannot do',
      'Written and tested at least 20 prompts across different tools',
      'Tried ChatGPT, Claude, Gemini, and Perplexity',
    ],
    related_tool_slugs: ['chatgpt', 'claude', 'gemini', 'perplexity', 'dall-e-3', 'elevenlabs'],
    related_model_slugs: ['gpt-4o', 'claude-3-5-sonnet'],
    related_skill_slugs: ['prompt-engineering-basics', 'write-system-prompts', 'ai-tool-selection'],
    confidence_score: 1.0,
    ai_generated: false,
    published_at: '2026-05-15T00:00:00Z',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
  {
    id: 'path-002',
    title: 'Build Your First AI Agent',
    slug: 'build-first-ai-agent',
    short_description: 'Design, build, and deploy an autonomous AI agent that completes multi-step tasks on its own.',
    long_description: 'Go from chat to agents. Learn to build autonomous AI systems that can plan, use tools, and complete complex tasks with minimal human intervention.',
    status: 'published',
    tags: ['developer', 'agents', 'advanced'],
    source_urls: [],
    goal: 'Build, deploy, and iterate on a real AI agent that completes multi-step tasks autonomously.',
    who_its_for: 'Developers, technical founders, and power users who want to go beyond chat.',
    required_skill_level: 'intermediate',
    estimated_hours: 18,
    modules: [
      { module: 1, title: 'What Is an AI Agent?', description: 'Architecture: goals, tools, memory, and loops.', skills: ['build-first-ai-agent'], tools: ['claude'], duration_hours: 2 },
      { module: 2, title: 'Build an Agent with Claude API', description: 'Tool use, reasoning loops, and error handling.', skills: ['build-first-ai-agent'], tools: ['claude', 'replit'], duration_hours: 4 },
      { module: 3, title: 'MCP: Model Context Protocol', description: 'Connect Claude to filesystem, DBs, and web tools.', skills: ['mcp-with-claude'], tools: ['claude'], duration_hours: 4 },
      { module: 4, title: 'No-Code Agents with n8n', description: 'Build powerful agents without coding.', skills: ['build-first-ai-agent'], tools: ['n8n', 'claude'], duration_hours: 4 },
      { module: 5, title: 'Multi-Agent Systems', description: 'Orchestrate multiple specialized agents.', skills: ['build-rag-system'], tools: ['claude', 'n8n'], duration_hours: 4 },
    ],
    practice_tasks: [
      'Build an agent that answers questions about a PDF by reading and reasoning over it',
      'Configure at least 3 MCP servers in Claude Desktop',
    ],
    mini_projects: [
      'Build a personal research agent that finds, reads, and summarizes relevant articles',
    ],
    completion_checklist: [
      'Understand the difference between a chatbot and an AI agent',
      'Built an agent with at least 2 tools',
      'Configured and used MCP servers in Claude Desktop',
    ],
    related_tool_slugs: ['claude', 'n8n', 'replit', 'cursor'],
    related_model_slugs: ['claude-3-5-sonnet', 'gpt-4o'],
    related_skill_slugs: ['build-first-ai-agent', 'mcp-with-claude', 'build-rag-system'],
    confidence_score: 1.0,
    ai_generated: false,
    published_at: '2026-05-15T00:00:00Z',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
]
