import type { Comparison } from '@/types/comparison'

export const MOCK_COMPARISONS: Comparison[] = [
  {
    id: 'c1',
    slug: 'chatgpt-vs-claude',
    title: 'ChatGPT vs Claude',
    short_description: 'Two leading AI assistants compared head-to-head. Which should you use in 2025?',
    comparison_type: 'head-to-head',
    item_slugs: ['gpt-4o', 'claude-3-5-sonnet'],
    item_type: 'model',
    verdict: 'For most users, GPT-4o edges out on speed and ecosystem breadth. Claude 3.5 Sonnet wins clearly for coding, long-document analysis, and users who want more nuanced, careful outputs. The best answer: use Claude for coding and analysis work, GPT-4o for everything else.',
    comparison_rows: [
      { field: 'provider',        label: 'Provider',         values: { 'gpt-4o': 'OpenAI',           'claude-3-5-sonnet': 'Anthropic' } },
      { field: 'context_window',  label: 'Context Window',   values: { 'gpt-4o': '128K tokens',       'claude-3-5-sonnet': '200K tokens' },   winner: 'claude-3-5-sonnet' },
      { field: 'pricing',         label: 'API Pricing',      values: { 'gpt-4o': '$2.50/M in',        'claude-3-5-sonnet': '$3/M in' },       winner: 'gpt-4o' },
      { field: 'free_plan',       label: 'Free Access',      values: { 'gpt-4o': 'ChatGPT free tier', 'claude-3-5-sonnet': 'Claude.ai free' } },
      { field: 'speed',           label: 'Speed',            values: { 'gpt-4o': 'Fast',              'claude-3-5-sonnet': 'Fast' } },
      { field: 'coding',          label: 'Coding (SWE)',     values: { 'gpt-4o': 'Excellent',         'claude-3-5-sonnet': 'Best in class' },  winner: 'claude-3-5-sonnet' },
      { field: 'writing',         label: 'Creative Writing', values: { 'gpt-4o': 'Excellent',         'claude-3-5-sonnet': 'Excellent' } },
      { field: 'vision',          label: 'Vision',           values: { 'gpt-4o': 'Yes (text+audio)',  'claude-3-5-sonnet': 'Yes (images)' } },
      { field: 'open_source',     label: 'Open Source',      values: { 'gpt-4o': 'No',               'claude-3-5-sonnet': 'No' } },
      { field: 'safety',          label: 'Safety Approach',  values: { 'gpt-4o': 'RLHF',             'claude-3-5-sonnet': 'Constitutional AI' } },
      { field: 'ecosystem',       label: 'Ecosystem',        values: { 'gpt-4o': 'Largest',          'claude-3-5-sonnet': 'Growing' },        winner: 'gpt-4o' },
    ],
    scenarios: [
      {
        title: 'Writing a 50-page research report',
        description: 'You need to analyze a large corpus of documents and produce a comprehensive report.',
        winner: 'claude-3-5-sonnet',
        reason: 'Claude\'s 200K context handles the full corpus. Its writing quality is more nuanced and it maintains consistency better across long outputs.',
      },
      {
        title: 'Building a Python web scraper',
        description: 'You need to write and debug a 200-line Python script that scrapes and parses data.',
        winner: 'claude-3-5-sonnet',
        reason: 'Claude 3.5 Sonnet leads on SWE-bench coding benchmarks. It understands complex code structures better and produces fewer bugs.',
      },
      {
        title: 'Answering customer support questions',
        description: 'You\'re building a chatbot that answers product questions from a knowledge base.',
        winner: 'gpt-4o',
        reason: 'GPT-4o is faster and has a larger ecosystem of integrations. The price-per-token is lower, which matters at high volume.',
      },
    ],
    recommendation_by_user_type: {
      beginner:  'Use ChatGPT (GPT-4o) — its free tier is generous, the interface is polished, and the community is larger.',
      creator:   'Slight edge to Claude for writing quality. Try both and pick the one whose style you prefer.',
      developer: 'Claude 3.5 Sonnet for coding tasks. GPT-4o for everything else.',
      business:  'GPT-4o for most workloads. Claude for document analysis and long-context tasks.',
    },
    status: 'published',
    published_at: '2024-10-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'c2',
    slug: 'chatgpt-vs-gemini',
    title: 'ChatGPT vs Gemini',
    short_description: 'OpenAI vs Google — which AI assistant wins in 2025?',
    comparison_type: 'head-to-head',
    item_slugs: ['gpt-4o', 'gemini-1-5-pro'],
    item_type: 'model',
    verdict: 'GPT-4o is the stronger general-purpose model. Gemini wins if you live in Google Workspace or need to process very long documents (1M context). For most users, GPT-4o is the better starting point.',
    comparison_rows: [
      { field: 'provider',       label: 'Provider',        values: { 'gpt-4o': 'OpenAI', 'gemini-1-5-pro': 'Google' } },
      { field: 'context_window', label: 'Context Window',  values: { 'gpt-4o': '128K tokens', 'gemini-1-5-pro': '1M tokens' }, winner: 'gemini-1-5-pro' },
      { field: 'pricing',        label: 'API Pricing',     values: { 'gpt-4o': '$2.50/M in', 'gemini-1-5-pro': '$3.50/M in (under 128K)' } },
      { field: 'speed',          label: 'Speed',           values: { 'gpt-4o': 'Fast', 'gemini-1-5-pro': 'Medium' }, winner: 'gpt-4o' },
      { field: 'coding',         label: 'Coding',          values: { 'gpt-4o': 'Excellent', 'gemini-1-5-pro': 'Good' }, winner: 'gpt-4o' },
      { field: 'workspace',      label: 'Google Workspace',values: { 'gpt-4o': 'Via plugins', 'gemini-1-5-pro': 'Native' }, winner: 'gemini-1-5-pro' },
      { field: 'vision',         label: 'Video Input',     values: { 'gpt-4o': 'No', 'gemini-1-5-pro': 'Yes (native)' }, winner: 'gemini-1-5-pro' },
      { field: 'ecosystem',      label: 'Ecosystem',       values: { 'gpt-4o': 'Largest', 'gemini-1-5-pro': 'Smaller but growing' }, winner: 'gpt-4o' },
    ],
    scenarios: [
      {
        title: 'Processing a 500-page PDF',
        description: 'Summarizing a very long document with complex sections.',
        winner: 'gemini-1-5-pro',
        reason: '1M token context handles it in one shot. GPT-4o needs chunking at 128K.',
      },
      {
        title: 'Daily work in Gmail and Google Docs',
        description: 'Using AI to help write emails, summarize meetings, and draft documents.',
        winner: 'gemini-1-5-pro',
        reason: 'Native integration with Workspace. No copy-pasting required.',
      },
      {
        title: 'Building a production app with AI',
        description: 'You need a reliable, well-documented API with a large community.',
        winner: 'gpt-4o',
        reason: 'OpenAI API is more mature, better documented, and has more community resources.',
      },
    ],
    recommendation_by_user_type: {
      beginner:  'ChatGPT for most things. Switch to Gemini if you use Google apps heavily.',
      creator:   'ChatGPT for writing. Gemini for video analysis and Google Docs integration.',
      developer: 'GPT-4o API. Gemini if you need very long context or video input.',
      business:  'GPT-4o for most workloads. Gemini for Google Workspace-heavy teams.',
    },
    status: 'published',
    published_at: '2024-10-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'c3',
    slug: 'best-model-for-coding',
    title: 'Best AI Model for Coding in 2025',
    short_description: 'Ranked: which AI model writes the best code, finds bugs fastest, and understands your codebase?',
    comparison_type: 'best-for',
    item_slugs: ['claude-3-5-sonnet', 'gpt-4o', 'o1', 'gpt-4o-mini'],
    item_type: 'model',
    verdict: 'Claude 3.5 Sonnet is the clear winner for coding in 2025. It scores highest on SWE-bench Verified (the most realistic coding benchmark), handles large codebases well with 200K context, and produces fewer bugs than GPT-4o. Use o1 for hard algorithmic problems. Use GPT-4o mini for high-volume simple tasks.',
    comparison_rows: [
      { field: 'model',           label: 'Model',             values: { 'claude-3-5-sonnet': 'Claude 3.5 Sonnet', 'gpt-4o': 'GPT-4o', 'o1': 'o1', 'gpt-4o-mini': 'GPT-4o mini' } },
      { field: 'swe_bench',       label: 'SWE-bench Score',   values: { 'claude-3-5-sonnet': '49% (best)',        'gpt-4o': '38%',    'o1': '41%',  'gpt-4o-mini': 'N/A' }, winner: 'claude-3-5-sonnet' },
      { field: 'context',         label: 'Context Window',    values: { 'claude-3-5-sonnet': '200K',              'gpt-4o': '128K',   'o1': '200K', 'gpt-4o-mini': '128K' }, winner: 'claude-3-5-sonnet' },
      { field: 'speed',           label: 'Speed',             values: { 'claude-3-5-sonnet': 'Fast',              'gpt-4o': 'Fast',   'o1': 'Slow', 'gpt-4o-mini': 'Very Fast' } },
      { field: 'cost',            label: 'API Cost',          values: { 'claude-3-5-sonnet': '$3/M',              'gpt-4o': '$2.50/M','o1': '$15/M','gpt-4o-mini': '$0.15/M' }, winner: 'gpt-4o-mini' },
      { field: 'best_use',        label: 'Best Use',          values: { 'claude-3-5-sonnet': 'All coding tasks',  'gpt-4o': 'General coding','o1': 'Hard algorithms','gpt-4o-mini': 'Simple tasks' } },
    ],
    scenarios: [
      {
        title: 'Debugging a production bug in a 10,000-line codebase',
        description: 'You need to find and fix a subtle bug across multiple files.',
        winner: 'claude-3-5-sonnet',
        reason: '200K context window + best SWE-bench score. It understands large codebases better than any other model.',
      },
      {
        title: 'Implementing a complex algorithm from scratch',
        description: 'Writing a novel pathfinding algorithm with complex edge cases.',
        winner: 'o1',
        reason: 'o1\'s reasoning mode excels at novel algorithmic problems that require step-by-step logical thinking.',
      },
      {
        title: 'Writing 1,000 unit tests automatically',
        description: 'Generating test cases at scale for cost efficiency.',
        winner: 'gpt-4o-mini',
        reason: 'Fast and cheap — at $0.15/M tokens, writing simple test cases costs 10x less than Claude or GPT-4o.',
      },
    ],
    recommendation_by_user_type: {
      beginner:  'Start with ChatGPT (GPT-4o) — the interface is familiar and it\'s free.',
      creator:   'GPT-4o for scripting and automation. Claude for reviewing longer codebases.',
      developer: 'Claude 3.5 Sonnet as your primary. o1 for hard problems. GPT-4o mini for bulk tasks.',
      business:  'Claude 3.5 Sonnet via the API or Cursor. o1 for complex architectural decisions.',
    },
    status: 'published',
    published_at: '2024-11-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'c4',
    slug: 'best-model-for-writing',
    title: 'Best AI Model for Writing in 2025',
    short_description: 'Which AI model produces the best writing? Ranked for blog posts, marketing copy, long-form, and creative writing.',
    comparison_type: 'best-for',
    item_slugs: ['claude-3-5-sonnet', 'gpt-4o', 'gemini-1-5-pro', 'gpt-4o-mini'],
    item_type: 'model',
    verdict: 'Claude 3.5 Sonnet and GPT-4o are neck-and-neck for most writing tasks. Claude is slightly preferred for nuanced, voice-driven writing and long-form content. GPT-4o is better for high-volume marketing copy. Both are significantly better than Gemini for pure writing quality.',
    comparison_rows: [
      { field: 'model',        label: 'Model',          values: { 'claude-3-5-sonnet': 'Claude 3.5 Sonnet', 'gpt-4o': 'GPT-4o', 'gemini-1-5-pro': 'Gemini 1.5 Pro', 'gpt-4o-mini': 'GPT-4o mini' } },
      { field: 'long_form',    label: 'Long-form',      values: { 'claude-3-5-sonnet': 'Best',              'gpt-4o': 'Excellent','gemini-1-5-pro': 'Good',           'gpt-4o-mini': 'Fair' },         winner: 'claude-3-5-sonnet' },
      { field: 'marketing',    label: 'Marketing Copy', values: { 'claude-3-5-sonnet': 'Excellent',         'gpt-4o': 'Best',    'gemini-1-5-pro': 'Good',           'gpt-4o-mini': 'Good' },         winner: 'gpt-4o' },
      { field: 'voice',        label: 'Voice/Tone',     values: { 'claude-3-5-sonnet': 'Exceptional',       'gpt-4o': 'Very good','gemini-1-5-pro': 'Good',          'gpt-4o-mini': 'Basic' },        winner: 'claude-3-5-sonnet' },
      { field: 'context',      label: 'Context Window', values: { 'claude-3-5-sonnet': '200K',              'gpt-4o': '128K',    'gemini-1-5-pro': '1M',             'gpt-4o-mini': '128K' } },
      { field: 'cost',         label: 'API Cost',       values: { 'claude-3-5-sonnet': '$3/M',              'gpt-4o': '$2.50/M', 'gemini-1-5-pro': '$3.50/M',        'gpt-4o-mini': '$0.15/M' },      winner: 'gpt-4o-mini' },
    ],
    scenarios: [
      {
        title: 'Writing a 5,000-word thought leadership article',
        description: 'Long-form content requiring a consistent voice and expert-level insights.',
        winner: 'claude-3-5-sonnet',
        reason: 'Claude maintains voice and consistency better across long outputs. Its writing feels more natural and less formulaic.',
      },
      {
        title: 'Generating 50 product descriptions in batch',
        description: 'E-commerce copy that needs to be good but produced at scale.',
        winner: 'gpt-4o-mini',
        reason: 'GPT-4o mini is 10-20x cheaper and produces acceptable quality for structured product copy.',
      },
      {
        title: 'Analyzing a competitor\'s content strategy',
        description: 'Processing 100 blog posts and synthesizing strategic insights.',
        winner: 'gemini-1-5-pro',
        reason: '1M context lets it process all 100 posts in a single call. Better than chunking with other models.',
      },
    ],
    recommendation_by_user_type: {
      beginner:  'Use ChatGPT Plus — GPT-4o through a polished interface.',
      creator:   'Try both Claude and GPT-4o. Claude for your own authentic voice. GPT-4o for faster bulk output.',
      developer: 'GPT-4o API for automated content pipelines. Claude API for quality-first workflows.',
      business:  'Claude for thought leadership and brand voice. GPT-4o for high-volume marketing automation.',
    },
    status: 'published',
    published_at: '2024-11-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
  },
]

export const FEATURED_COMPARISONS = [
  { slug: 'chatgpt-vs-claude',    label: 'ChatGPT vs Claude',              type: 'head-to-head' as const },
  { slug: 'chatgpt-vs-gemini',    label: 'ChatGPT vs Gemini',              type: 'head-to-head' as const },
  { slug: 'best-model-for-coding', label: 'Best Model for Coding',         type: 'best-for' as const },
  { slug: 'best-model-for-writing', label: 'Best Model for Writing',       type: 'best-for' as const },
]
