import type { Model } from '@/types/model'

export const MOCK_MODELS: Model[] = [
  {
    id: 'm1',
    title: 'GPT-4o',
    slug: 'gpt-4o',
    short_description: "OpenAI's fastest flagship model. Multimodal, fast, and capable across text, vision, and audio.",
    long_description: 'GPT-4o ("o" for omni) is OpenAI\'s flagship multimodal model that accepts any combination of text, audio, and image inputs and produces text, audio, and image outputs. It matches GPT-4 Turbo on intelligence while being significantly faster and cheaper, making it the default choice for most applications.',
    provider: 'OpenAI',
    model_type: 'llm',
    current_status: 'active',
    release_date: '2024-05-13',
    official_source_url: 'https://platform.openai.com/docs/models/gpt-4o',
    context_window: 128000,
    input_types: ['text', 'image', 'audio'],
    output_types: ['text', 'audio'],
    is_open_source: false,
    has_api: true,
    speed: 'fast',
    best_for: ['General tasks', 'Writing', 'Coding', 'Vision analysis', 'Conversational AI', 'Real-time apps'],
    not_ideal_for: ['Complex multi-step reasoning (use o1)', 'Privacy-sensitive local inference'],
    strengths: ['Fastest frontier model', 'Native multimodal (text + vision + audio)', 'Best price-to-performance ratio', 'Massive third-party ecosystem', 'Excellent instruction following'],
    weaknesses: ['Knowledge cutoff', 'Can hallucinate on niche topics', 'Closed source', 'API costs at scale'],
    speed_notes: 'Very fast — typically under 1s first token.',
    quality_notes: 'Best-in-class for most tasks. Matches or exceeds GPT-4 Turbo at lower cost.',
    safety_notes: 'Strong RLHF alignment. Refuses harmful content reliably.',
    pricing_model: 'paid',
    pricing_summary: 'Free via ChatGPT. API: $2.50/M input tokens, $10/M output tokens.',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: ['chatgpt', 'cursor'],
    related_model_slugs: ['gpt-4o-mini', 'o1', 'claude-3-5-sonnet'],
    related_skill_slugs: ['prompt-engineering'],
    example_prompts: [
      'Analyze this image and describe what you see in detail.',
      'Write a Python function that sorts a list of dictionaries by a given key.',
      'Summarize this 10-page report into 5 bullet points.',
    ],
    tags: ['llm', 'multimodal', 'openai', 'flagship'],
    use_cases: ['writing', 'coding', 'vision', 'conversational-ai'],
    status: 'published',
    source_urls: ['https://platform.openai.com/docs/models/gpt-4o'],
    created_at: '2024-05-13T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-05-13T00:00:00Z',
    confidence_score: 0.98,
    ai_generated: false,
  },
  {
    id: 'm2',
    title: 'GPT-4o mini',
    slug: 'gpt-4o-mini',
    short_description: "OpenAI's small, fast, cheap model for high-volume tasks. Replaces GPT-3.5 Turbo.",
    long_description: 'GPT-4o mini is OpenAI\'s most cost-efficient small model. It scores 82% on MMLU and is designed for high-volume, latency-sensitive tasks. It supports text and vision and is perfect for classification, extraction, simple Q&A, and any task where you run millions of calls per month.',
    provider: 'OpenAI',
    model_type: 'llm',
    current_status: 'active',
    release_date: '2024-07-18',
    official_source_url: 'https://platform.openai.com/docs/models/gpt-4o-mini',
    context_window: 128000,
    input_types: ['text', 'image'],
    output_types: ['text'],
    is_open_source: false,
    has_api: true,
    speed: 'very_fast',
    best_for: ['High-volume tasks', 'Classification', 'Data extraction', 'Simple Q&A', 'Chatbots', 'Cost-sensitive workloads'],
    not_ideal_for: ['Complex reasoning', 'Long-form creative writing', 'Expert-level coding'],
    strengths: ['Very cheap ($0.15/M input)', 'Very fast', '128K context', 'Good instruction following', 'Vision support'],
    weaknesses: ['Less capable than GPT-4o on complex tasks', 'Not ideal for nuanced creative tasks'],
    speed_notes: 'Extremely fast — sub-500ms first token typical.',
    quality_notes: 'Best small model for price/performance. Use for anything GPT-3.5 was used for.',
    safety_notes: 'Same alignment as GPT-4o.',
    pricing_model: 'paid',
    pricing_summary: 'API: $0.15/M input tokens, $0.60/M output tokens.',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: ['chatgpt'],
    related_model_slugs: ['gpt-4o', 'claude-3-haiku', 'gemini-1-5-flash'],
    related_skill_slugs: ['prompt-engineering', 'ai-agents'],
    example_prompts: [
      'Classify this support ticket into one of: billing, technical, feature-request, other.',
      'Extract the company name, date, and total amount from this invoice text.',
    ],
    tags: ['llm', 'small', 'fast', 'cheap', 'openai'],
    use_cases: ['classification', 'extraction', 'chatbot', 'automation'],
    status: 'published',
    source_urls: ['https://platform.openai.com/docs/models/gpt-4o-mini'],
    created_at: '2024-07-18T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-07-18T00:00:00Z',
    confidence_score: 0.97,
    ai_generated: false,
  },
  {
    id: 'm3',
    title: 'o1',
    slug: 'o1',
    short_description: "OpenAI's reasoning model that thinks before it responds. Best for hard math, science, and complex coding.",
    long_description: 'o1 is OpenAI\'s first reasoning model. It spends more time "thinking" before answering — generating an internal chain-of-thought that dramatically improves performance on hard problems. It outperforms PhD-level humans on physics, chemistry, and biology benchmarks, and scores in the 89th percentile on competitive programming.',
    provider: 'OpenAI',
    model_type: 'reasoning',
    current_status: 'active',
    release_date: '2024-12-05',
    official_source_url: 'https://platform.openai.com/docs/models/o1',
    context_window: 200000,
    input_types: ['text', 'image'],
    output_types: ['text'],
    is_open_source: false,
    has_api: true,
    speed: 'slow',
    best_for: ['Complex math', 'Scientific reasoning', 'Hard coding problems', 'Multi-step logic', 'Research analysis'],
    not_ideal_for: ['Simple tasks (wasteful)', 'Real-time applications', 'Creative writing'],
    strengths: ['PhD-level reasoning', 'Best on hard benchmark problems', '200K context', 'Excellent at structured output'],
    weaknesses: ['Slow — 10–30s latency typical', 'Expensive ($15/M input)', 'Overkill for simple tasks', 'No system prompt support initially'],
    speed_notes: 'Slow by design — thinking takes time. Not for real-time use.',
    quality_notes: 'Best model for hard reasoning. Use it when GPT-4o fails.',
    safety_notes: 'Strong safety training. Internal reasoning chain not exposed.',
    pricing_model: 'paid',
    pricing_summary: 'API: $15/M input tokens, $60/M output tokens.',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: ['cursor', 'chatgpt'],
    related_model_slugs: ['gpt-4o', 'claude-3-5-sonnet'],
    related_skill_slugs: ['prompt-engineering'],
    example_prompts: [
      'Prove that the sum of the first n odd numbers equals n².',
      'Debug this complex recursive algorithm and explain why it fails on edge case X.',
    ],
    tags: ['reasoning', 'math', 'science', 'openai', 'slow'],
    use_cases: ['research', 'coding', 'math', 'science'],
    status: 'published',
    source_urls: ['https://platform.openai.com/docs/models/o1'],
    created_at: '2024-12-05T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-12-05T00:00:00Z',
    confidence_score: 0.96,
    ai_generated: false,
  },
  {
    id: 'm4',
    title: 'Claude 3.5 Sonnet',
    slug: 'claude-3-5-sonnet',
    short_description: "Anthropic's best model. Exceptional at coding, nuanced writing, and long-document analysis.",
    long_description: 'Claude 3.5 Sonnet is Anthropic\'s flagship model, striking the best balance between intelligence and speed. It leads on coding benchmarks (SWE-bench Verified), excels at nuanced writing, and handles 200K token contexts better than any competing model. Used by Cursor, GitHub Copilot, and many enterprise apps.',
    provider: 'Anthropic',
    model_type: 'llm',
    current_status: 'active',
    release_date: '2024-10-22',
    official_source_url: 'https://docs.anthropic.com/claude/docs/models-overview',
    context_window: 200000,
    input_types: ['text', 'image'],
    output_types: ['text'],
    is_open_source: false,
    has_api: true,
    speed: 'fast',
    best_for: ['Coding', 'Long-document analysis', 'Nuanced writing', 'Code review', 'Complex instruction following'],
    not_ideal_for: ['Real-time audio', 'Image generation', 'Simple tasks (use Haiku)'],
    strengths: ['#1 on SWE-bench coding benchmark', '200K context, actually uses it well', 'Best for nuanced writing', 'Strong refusal of harmful content', 'Excellent structured output'],
    weaknesses: ['No image generation', 'Knowledge cutoff', 'Slightly slower than GPT-4o', 'No free API tier'],
    speed_notes: 'Fast. Comparable to GPT-4o. 200K context adds latency on long inputs.',
    quality_notes: 'Best model for coding and long-doc tasks. Strong competitor to GPT-4o.',
    safety_notes: 'Constitutional AI training. More cautious than GPT-4o on edge cases.',
    pricing_model: 'paid',
    pricing_summary: 'API: $3/M input tokens, $15/M output tokens. Free via Claude.ai.',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: ['claude', 'cursor'],
    related_model_slugs: ['gpt-4o', 'claude-3-haiku', 'gemini-1-5-pro'],
    related_skill_slugs: ['prompt-engineering', 'ai-coding'],
    example_prompts: [
      'Review this 500-line Python file for bugs, performance issues, and style violations.',
      'Analyze the key arguments in this 80-page academic paper.',
    ],
    tags: ['llm', 'coding', 'anthropic', 'flagship'],
    use_cases: ['coding', 'writing', 'analysis', 'agents'],
    status: 'published',
    source_urls: ['https://docs.anthropic.com/claude/docs/models-overview'],
    created_at: '2024-10-22T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-10-22T00:00:00Z',
    confidence_score: 0.97,
    ai_generated: false,
  },
  {
    id: 'm5',
    title: 'Claude 3 Haiku',
    slug: 'claude-3-haiku',
    short_description: "Anthropic's fastest, cheapest model. Built for high-volume, latency-sensitive workloads.",
    long_description: "Claude 3 Haiku is Anthropic's smallest and fastest model. It's designed for enterprise tasks that require immediate responses: customer support, content moderation, data extraction, and real-time summarization. It processes dense research papers with charts and graphs faster than any comparable model.",
    provider: 'Anthropic',
    model_type: 'llm',
    current_status: 'active',
    release_date: '2024-03-13',
    official_source_url: 'https://docs.anthropic.com/claude/docs/models-overview',
    context_window: 200000,
    input_types: ['text', 'image'],
    output_types: ['text'],
    is_open_source: false,
    has_api: true,
    speed: 'very_fast',
    best_for: ['High-volume automation', 'Customer support', 'Content moderation', 'Data extraction', 'Simple summarization'],
    not_ideal_for: ['Complex reasoning', 'Creative long-form writing', 'Expert-level coding'],
    strengths: ['Very cheap ($0.25/M input)', 'Very fast', 'Good for structured tasks', '200K context', 'Vision support'],
    weaknesses: ['Less capable than Sonnet on complex tasks', 'Not ideal for nuanced writing'],
    speed_notes: 'Fastest Anthropic model. Sub-500ms typical.',
    quality_notes: 'Best Anthropic model for cost-sensitive workloads.',
    safety_notes: 'Same Constitutional AI as other Claude models.',
    pricing_model: 'paid',
    pricing_summary: 'API: $0.25/M input, $1.25/M output.',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: ['claude'],
    related_model_slugs: ['claude-3-5-sonnet', 'gpt-4o-mini', 'gemini-1-5-flash'],
    related_skill_slugs: ['prompt-engineering', 'ai-agents'],
    example_prompts: [
      'Is this customer message positive, neutral, or negative? Respond with one word.',
      'Extract the name, email, and phone number from this contact form submission.',
    ],
    tags: ['llm', 'small', 'fast', 'cheap', 'anthropic'],
    use_cases: ['automation', 'classification', 'moderation', 'extraction'],
    status: 'published',
    source_urls: ['https://docs.anthropic.com/claude/docs/models-overview'],
    created_at: '2024-03-13T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-03-13T00:00:00Z',
    confidence_score: 0.95,
    ai_generated: false,
  },
  {
    id: 'm6',
    title: 'Gemini 1.5 Pro',
    slug: 'gemini-1-5-pro',
    short_description: "Google's best model. Industry-leading 1M token context window and deep Google ecosystem integration.",
    long_description: "Gemini 1.5 Pro is Google's frontier model, featuring a breakthrough 1 million token context window — large enough to process an entire codebase, a full novel, or hours of video in a single request. It's deeply integrated with Google Workspace, YouTube, and Google Search, making it uniquely powerful for users in the Google ecosystem.",
    provider: 'Google',
    model_type: 'llm',
    current_status: 'active',
    release_date: '2024-05-14',
    official_source_url: 'https://ai.google.dev/gemini-api/docs/models/gemini',
    context_window: 1000000,
    input_types: ['text', 'image', 'audio', 'video'],
    output_types: ['text'],
    is_open_source: false,
    has_api: true,
    speed: 'medium',
    best_for: ['Very long documents', 'Video analysis', 'Audio transcription + analysis', 'Google Workspace tasks', 'Research across large corpora'],
    not_ideal_for: ['Simple tasks (too expensive)', 'Real-time low-latency apps'],
    strengths: ['1M token context window', 'Native video and audio input', 'Deep Google integration', 'Competitive on most benchmarks', 'Free tier via AI Studio'],
    weaknesses: ['Slower than GPT-4o and Claude 3.5', 'Google data privacy concerns', 'Less third-party ecosystem', 'API less mature than OpenAI'],
    speed_notes: 'Medium speed. 1M context incurs latency on very long inputs.',
    quality_notes: 'Excellent model. Best when you need very long context or Google integrations.',
    safety_notes: 'Google safety training. Comparable to OpenAI and Anthropic.',
    pricing_model: 'freemium',
    pricing_summary: 'Free tier via AI Studio. API: $3.50/M tokens (under 128K), $7/M (over 128K).',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: ['gemini'],
    related_model_slugs: ['gpt-4o', 'claude-3-5-sonnet', 'gemini-1-5-flash'],
    related_skill_slugs: ['prompt-engineering', 'research'],
    example_prompts: [
      'Here is a 500-page PDF. Summarize every major finding across all chapters.',
      'Watch this 1-hour video and extract every action item mentioned.',
    ],
    tags: ['llm', 'google', 'long-context', 'multimodal', 'flagship'],
    use_cases: ['research', 'analysis', 'video', 'google-workspace'],
    status: 'published',
    source_urls: ['https://ai.google.dev/gemini-api/docs/models/gemini'],
    created_at: '2024-05-14T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-05-14T00:00:00Z',
    confidence_score: 0.96,
    ai_generated: false,
  },
  {
    id: 'm7',
    title: 'Gemini 1.5 Flash',
    slug: 'gemini-1-5-flash',
    short_description: "Google's fast, efficient model. 1M context at a fraction of Pro's cost.",
    long_description: "Gemini 1.5 Flash is Google's speed-optimized model. It retains the breakthrough 1M token context window of Gemini 1.5 Pro but runs significantly faster and at far lower cost. It's designed for tasks where speed matters: summarization, chat, captioning, and data extraction at scale.",
    provider: 'Google',
    model_type: 'llm',
    current_status: 'active',
    release_date: '2024-05-24',
    official_source_url: 'https://ai.google.dev/gemini-api/docs/models/gemini',
    context_window: 1000000,
    input_types: ['text', 'image', 'audio', 'video'],
    output_types: ['text'],
    is_open_source: false,
    has_api: true,
    speed: 'fast',
    best_for: ['High-volume summarization', 'Chat applications', 'Cost-sensitive long-context tasks', 'Image captioning at scale'],
    not_ideal_for: ['Complex multi-step reasoning', 'Expert-level coding'],
    strengths: ['1M context at low cost', 'Fast response times', 'Free tier', 'Multimodal', 'Good for scale'],
    weaknesses: ['Less capable than Pro on hard tasks', 'Google ecosystem lock-in'],
    speed_notes: 'Fast. Much faster than 1.5 Pro for same context length.',
    quality_notes: 'Good trade-off. Use when 1.5 Pro is overkill but you need long context.',
    safety_notes: 'Same as 1.5 Pro.',
    pricing_model: 'freemium',
    pricing_summary: 'Free tier. API: $0.075/M tokens (under 128K), $0.15/M (over 128K).',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: ['gemini'],
    related_model_slugs: ['gemini-1-5-pro', 'gpt-4o-mini', 'claude-3-haiku'],
    related_skill_slugs: ['prompt-engineering'],
    example_prompts: [
      'Summarize this 100-page document into a 1-page executive summary.',
      'Describe what is happening in each frame of this video.',
    ],
    tags: ['llm', 'google', 'fast', 'long-context', 'efficient'],
    use_cases: ['summarization', 'chat', 'automation', 'scale'],
    status: 'published',
    source_urls: ['https://ai.google.dev/gemini-api/docs/models/gemini'],
    created_at: '2024-05-24T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-05-24T00:00:00Z',
    confidence_score: 0.95,
    ai_generated: false,
  },
  {
    id: 'm8',
    title: 'Llama 3.1 70B',
    slug: 'llama-3-1-70b',
    short_description: "Meta's flagship open-source model. Run it locally or on any cloud provider — no API required.",
    long_description: "Llama 3.1 70B is Meta's most capable open-source LLM. It rivals GPT-4o and Claude 3.5 Sonnet on many benchmarks while being fully open: download the weights, run it locally, fine-tune it on your data, and deploy it without paying per-token API fees. The 70B size is the sweet spot — powerful enough for most tasks, runnable on a high-end GPU.",
    provider: 'Meta',
    model_type: 'llm',
    current_status: 'active',
    release_date: '2024-07-23',
    official_source_url: 'https://llama.meta.com/',
    context_window: 128000,
    input_types: ['text'],
    output_types: ['text'],
    is_open_source: true,
    has_api: true,
    speed: 'medium',
    best_for: ['Privacy-sensitive tasks', 'On-premise deployment', 'Fine-tuning on custom data', 'Cost at scale', 'Research'],
    not_ideal_for: ['Out-of-the-box use without setup', 'Teams without infrastructure'],
    strengths: ['Fully open source', 'Self-hostable', 'No per-token cost at inference', 'Fine-tunable', 'Strong benchmark performance', 'Privacy — your data stays local'],
    weaknesses: ['Requires GPU infrastructure to run', 'Slower than GPT-4o/Claude hosted', 'No multimodal support', 'Setup complexity'],
    speed_notes: 'Speed depends entirely on your hardware. H100 GPU gives fast results.',
    quality_notes: 'Rivals GPT-4o on many benchmarks. Best open-source model available.',
    safety_notes: 'Meta safety training. Less conservative than Claude. Users responsible for deployment safety.',
    pricing_model: 'open-source',
    pricing_summary: 'Free weights. Pay only for compute (self-host) or via Together AI, Groq, etc.',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: ['n8n'],
    related_model_slugs: ['gpt-4o', 'claude-3-5-sonnet', 'mistral-large'],
    related_skill_slugs: ['ai-agents', 'prompt-engineering'],
    example_prompts: [
      'Generate a dataset of 100 customer support conversations for fine-tuning.',
      'Write a detailed technical specification for a REST API endpoint.',
    ],
    tags: ['llm', 'open-source', 'meta', 'self-host', 'privacy'],
    use_cases: ['self-hosting', 'fine-tuning', 'privacy', 'research'],
    status: 'published',
    source_urls: ['https://llama.meta.com/', 'https://ai.meta.com/blog/meta-llama-3-1/'],
    created_at: '2024-07-23T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-07-23T00:00:00Z',
    confidence_score: 0.94,
    ai_generated: false,
  },
  {
    id: 'm9',
    title: 'Mistral Large',
    slug: 'mistral-large',
    short_description: "Mistral's flagship model. EU-based, GDPR-compliant, and excellent at multilingual tasks.",
    long_description: "Mistral Large is the flagship model from Mistral AI, the French AI company building the European alternative to US frontier models. It excels at multilingual tasks (English, French, Spanish, German, Italian), supports function calling, and is available with GDPR-compliant EU data processing — making it the go-to choice for European businesses.",
    provider: 'Mistral',
    model_type: 'llm',
    current_status: 'active',
    release_date: '2024-02-26',
    official_source_url: 'https://docs.mistral.ai/getting-started/models/',
    context_window: 128000,
    input_types: ['text'],
    output_types: ['text'],
    is_open_source: false,
    has_api: true,
    speed: 'fast',
    best_for: ['European enterprises', 'GDPR compliance', 'Multilingual tasks', 'Function calling', 'Code generation'],
    not_ideal_for: ['Vision tasks', 'Very long contexts beyond 32K practically'],
    strengths: ['EU-based (GDPR compliant)', 'Excellent multilingual', 'Strong coding', 'Good price-performance', 'Native function calling'],
    weaknesses: ['Less ecosystem than OpenAI/Anthropic', 'No vision support', 'Smaller community'],
    speed_notes: 'Fast. Competitive with GPT-4o.',
    quality_notes: 'Strong model. Best for EU compliance use cases. Competitive on most benchmarks.',
    safety_notes: 'Mistral safety training. More permissive than Claude, less than GPT-4o on some topics.',
    pricing_model: 'paid',
    pricing_summary: 'API: €0.002/1K tokens (La Plateforme). Azure and GCP also available.',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: [],
    related_model_slugs: ['gpt-4o', 'claude-3-5-sonnet', 'llama-3-1-70b'],
    related_skill_slugs: ['prompt-engineering'],
    example_prompts: [
      'Translate this legal contract from English to French, preserving formal register.',
      'Write a Python function that calls this REST API endpoint with proper error handling.',
    ],
    tags: ['llm', 'eu', 'gdpr', 'multilingual', 'mistral'],
    use_cases: ['multilingual', 'gdpr', 'coding', 'enterprise'],
    status: 'published',
    source_urls: ['https://docs.mistral.ai/getting-started/models/'],
    created_at: '2024-02-26T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-02-26T00:00:00Z',
    confidence_score: 0.93,
    ai_generated: false,
  },
  {
    id: 'm10',
    title: 'DALL-E 3',
    slug: 'dall-e-3',
    short_description: "OpenAI's text-to-image model. Highest prompt adherence of any image generator.",
    long_description: "DALL-E 3 is OpenAI's image generation model, integrated directly into ChatGPT and available via API. It dramatically improves on DALL-E 2 with far better prompt adherence — it generates exactly what you describe, handles complex compositions, and produces text within images more reliably than Midjourney or Stable Diffusion.",
    provider: 'OpenAI',
    model_type: 'image',
    current_status: 'active',
    release_date: '2023-10-19',
    official_source_url: 'https://platform.openai.com/docs/guides/images',
    context_window: undefined,
    input_types: ['text'],
    output_types: ['image'],
    is_open_source: false,
    has_api: true,
    speed: 'medium',
    best_for: ['Marketing visuals', 'Concept art', 'Illustrations', 'Product mockups', 'Social content'],
    not_ideal_for: ['Photorealistic product photography', 'Fine-grained artistic style control'],
    strengths: ['Best prompt adherence', 'Text in images works', 'ChatGPT integration', 'Consistent with detailed descriptions', 'Good for non-designers'],
    weaknesses: ['Less artistic than Midjourney', 'Cannot do photorealistic renders', 'No style references', 'Closed source'],
    speed_notes: 'Medium — 5-15 seconds per image.',
    quality_notes: 'Best for exact prompt adherence. Midjourney wins on artistic quality.',
    safety_notes: 'Strict content policy. Refuses explicit content and real people.',
    pricing_model: 'paid',
    pricing_summary: 'Via API: $0.04-$0.08 per image (1024x1024). Included in ChatGPT Plus.',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: ['chatgpt', 'midjourney'],
    related_model_slugs: [],
    related_skill_slugs: ['image-prompting', 'prompt-engineering'],
    example_prompts: [
      'A photorealistic product shot of a black coffee mug on a white marble table, studio lighting.',
      'Digital art illustration of a futuristic city skyline at sunset, teal and orange color palette.',
    ],
    tags: ['image', 'text-to-image', 'openai', 'dall-e'],
    use_cases: ['image-generation', 'marketing', 'design'],
    status: 'published',
    source_urls: ['https://platform.openai.com/docs/guides/images'],
    created_at: '2023-10-19T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2023-10-19T00:00:00Z',
    confidence_score: 0.95,
    ai_generated: false,
  },
  {
    id: 'm11',
    title: 'Whisper',
    slug: 'whisper',
    short_description: "OpenAI's open-source speech-to-text model. 99 languages, free to run locally.",
    long_description: "Whisper is OpenAI's open-source automatic speech recognition (ASR) model. Trained on 680,000 hours of multilingual audio, it handles accents, technical jargon, background noise, and 99 languages. It's completely free to download and run, and the API version costs a fraction of Google Cloud Speech. Used in Otter.ai, Descript, and thousands of apps.",
    provider: 'OpenAI',
    model_type: 'audio',
    current_status: 'active',
    release_date: '2022-09-21',
    official_source_url: 'https://platform.openai.com/docs/models/whisper',
    context_window: undefined,
    input_types: ['audio'],
    output_types: ['text'],
    is_open_source: true,
    has_api: true,
    speed: 'fast',
    best_for: ['Transcription', 'Subtitles', 'Voice commands', 'Meeting notes', 'Podcast transcription'],
    not_ideal_for: ['Real-time streaming (latency)', 'Speaker diarization (who said what)'],
    strengths: ['99 languages', 'Open source & free to self-host', 'Handles noise well', 'API is very cheap', 'Works offline'],
    weaknesses: ['No real-time streaming', 'No speaker identification', 'Punctuation can be inconsistent'],
    speed_notes: 'Fast for batch transcription. Not suitable for real-time streaming.',
    quality_notes: 'Best open-source ASR. Competitive with Google Cloud Speech.',
    safety_notes: 'Open weights — no safety restrictions. Users responsible for use.',
    pricing_model: 'open-source',
    pricing_summary: 'Free to self-host. OpenAI API: $0.006/minute.',
    pricing_last_verified: '2025-05-01',
    related_tool_slugs: ['elevenlabs'],
    related_model_slugs: [],
    related_skill_slugs: ['ai-voice', 'content-creation'],
    example_prompts: [],
    tags: ['audio', 'speech-to-text', 'open-source', 'transcription', 'openai'],
    use_cases: ['transcription', 'voice', 'subtitles', 'automation'],
    status: 'published',
    source_urls: ['https://platform.openai.com/docs/models/whisper', 'https://github.com/openai/whisper'],
    created_at: '2022-09-21T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2022-09-21T00:00:00Z',
    confidence_score: 0.96,
    ai_generated: false,
  },
]

export const MODEL_PROVIDERS = [
  'OpenAI',
  'Anthropic',
  'Google',
  'Meta',
  'Mistral',
  'Stability AI',
  'Cohere',
  'AI21',
]

export const MODEL_TYPES = [
  { value: 'llm',       label: 'LLM',       icon: 'psychology' },
  { value: 'reasoning', label: 'Reasoning',  icon: 'calculate' },
  { value: 'image',     label: 'Image Gen',  icon: 'image' },
  { value: 'audio',     label: 'Audio',      icon: 'mic' },
  { value: 'video',     label: 'Video',      icon: 'movie' },
  { value: 'embedding', label: 'Embedding',  icon: 'hub' },
  { value: 'coding',    label: 'Coding',     icon: 'code' },
]
