import type { Skill } from '@/types/skill'

export const MOCK_SKILLS: Skill[] = [
  {
    id: 'skill-001',
    title: 'Prompt Engineering Basics',
    slug: 'prompt-engineering-basics',
    short_description: 'Learn to write clear, effective prompts that get consistent, high-quality results from any AI model.',
    long_description: 'Prompt engineering is the skill of communicating effectively with AI models. Learn how to structure requests, provide context, set output formats, and iterate to get exactly what you need.',
    status: 'published',
    tags: ['llm', 'writing', 'beginner'],
    source_urls: ['https://platform.openai.com/docs/guides/prompt-engineering'],
    difficulty: 'beginner',
    estimated_hours: 3,
    who_should_learn: 'Anyone who uses AI tools regularly and wants to get better results.',
    why_it_matters: 'The quality of your prompt determines the quality of the output. Better prompts = better results every time.',
    use_cases: ['writing', 'coding', 'research'],
    learning_steps: [
      { step: 1, title: 'Understand how LLMs work', description: 'Learn the basics of how language models process and respond to text.', duration_hours: 0.5 },
      { step: 2, title: 'The anatomy of a good prompt', description: 'Role, task, context, format, and constraints.', duration_hours: 0.5 },
      { step: 3, title: 'Common prompt patterns', description: 'Zero-shot, few-shot, chain-of-thought, and structured output prompts.', duration_hours: 1 },
      { step: 4, title: 'Iterating and refining', description: 'How to diagnose bad outputs and fix them.', duration_hours: 0.5 },
      { step: 5, title: 'Build your prompt library', description: 'Create reusable prompts for your most common tasks.', duration_hours: 0.5 },
    ],
    practical_examples: [
      'Write a prompt that generates a weekly email newsletter summary',
      'Create a prompt that extracts key points from any article',
    ],
    common_mistakes: [
      'Being too vague — "write something about marketing" vs. "write a 200-word Instagram caption for a SaaS product launch targeting solo founders"',
      'Forgetting to specify output format',
      'Not providing enough context about the audience',
    ],
    required_tool_slugs: ['chatgpt'],
    related_tool_slugs: ['claude', 'gemini', 'perplexity'],
    related_model_slugs: ['gpt-4o', 'claude-3-5-sonnet'],
    related_skill_slugs: ['write-system-prompts', 'build-first-ai-agent'],
    recommended_prompt_slugs: [],
    confidence_score: 1.0,
    ai_generated: false,
    published_at: '2026-05-15T00:00:00Z',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
  {
    id: 'skill-002',
    title: 'Build an AI Chatbot (no-code)',
    slug: 'build-ai-chatbot-no-code',
    short_description: 'Build a custom AI chatbot for your website or business using no-code tools — no programming required.',
    long_description: 'Build a working AI chatbot that can answer questions about your business, handle FAQs, and escalate complex issues to humans — all without writing a line of code.',
    status: 'published',
    tags: ['no-code', 'automation', 'chatbot'],
    source_urls: ['https://n8n.io/docs'],
    difficulty: 'beginner',
    estimated_hours: 5,
    who_should_learn: 'Business owners, marketers, and operators who want to automate customer interactions.',
    why_it_matters: 'A chatbot that answers 80% of FAQs automatically saves hours of support time weekly.',
    use_cases: ['customer support', 'automation'],
    learning_steps: [
      { step: 1, title: 'Define your chatbot scope', description: 'Decide what questions it will answer and what it will not.', duration_hours: 0.5 },
      { step: 2, title: 'Prepare your knowledge base', description: 'Write or compile the answers your chatbot needs.', duration_hours: 1 },
      { step: 3, title: 'Build with n8n or a no-code tool', description: 'Connect an LLM to your knowledge base.', duration_hours: 2 },
      { step: 4, title: 'Test and refine', description: 'Ask hard questions and fix gaps.', duration_hours: 1 },
      { step: 5, title: 'Deploy and monitor', description: 'Embed on your site or connect to Slack/email.', duration_hours: 0.5 },
    ],
    practical_examples: [
      'A support bot that answers FAQs about your product',
      'A booking assistant that checks availability and books calls',
    ],
    common_mistakes: [
      'Making the scope too broad — start with 10-15 specific FAQs',
      'Not testing edge cases and off-topic questions',
      'Forgetting to set up human handoff for complex issues',
    ],
    required_tool_slugs: ['n8n'],
    related_tool_slugs: ['chatgpt', 'claude', 'zapier'],
    related_model_slugs: ['gpt-4o-mini', 'claude-3-5-haiku'],
    related_skill_slugs: ['prompt-engineering-basics', 'automate-customer-support'],
    recommended_prompt_slugs: [],
    confidence_score: 1.0,
    ai_generated: false,
    published_at: '2026-05-15T00:00:00Z',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
  {
    id: 'skill-003',
    title: 'Build Your First AI Agent',
    slug: 'build-first-ai-agent',
    short_description: 'Design and build an autonomous AI agent that can take actions and complete multi-step tasks.',
    long_description: 'AI agents are autonomous systems that use LLMs to plan, reason, and take actions using tools. Learn to build one from scratch.',
    status: 'published',
    tags: ['agent', 'developer', 'advanced'],
    source_urls: ['https://docs.anthropic.com/claude/docs'],
    difficulty: 'intermediate',
    estimated_hours: 8,
    who_should_learn: 'Developers and technical founders who want to build autonomous AI systems.',
    why_it_matters: 'Agents can automate complex multi-step tasks that are impossible for simple chatbots.',
    use_cases: ['automation', 'research', 'coding'],
    learning_steps: [
      { step: 1, title: 'Understand the agent architecture', description: 'Goals, tools, memory, and action loops.', duration_hours: 1 },
      { step: 2, title: 'Set up the Anthropic API', description: 'API key, client setup, first test call.', duration_hours: 0.5 },
      { step: 3, title: 'Add tool use', description: 'Give your agent web search and file writing.', duration_hours: 2 },
      { step: 4, title: 'Build a reasoning loop', description: 'Let the agent think, act, observe, and repeat.', duration_hours: 3 },
      { step: 5, title: 'Deploy and test on a real task', description: 'Give it a real problem and evaluate.', duration_hours: 1.5 },
    ],
    practical_examples: [
      'A research agent that finds and summarizes articles on any topic',
      'A code review agent that reads PRs and suggests improvements',
    ],
    common_mistakes: [
      'Building too complex an agent on first try — start with 2 tools maximum',
      'Not adding error handling for tool failures',
      'Not testing the agent on adversarial inputs',
    ],
    required_tool_slugs: ['claude', 'replit'],
    related_tool_slugs: ['n8n', 'cursor'],
    related_model_slugs: ['claude-3-5-sonnet', 'gpt-4o'],
    related_skill_slugs: ['prompt-engineering-basics', 'mcp-with-claude', 'build-rag-system'],
    recommended_prompt_slugs: [],
    confidence_score: 1.0,
    ai_generated: false,
    published_at: '2026-05-15T00:00:00Z',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
]
