import type { GlossaryTerm } from '@/types/glossary'

export const MOCK_GLOSSARY: GlossaryTerm[] = [
  {
    id: 'g-001',
    title: 'LLM (Large Language Model)',
    slug: 'llm',
    simple_definition: 'A type of AI trained on massive amounts of text that can understand and generate human language.',
    full_explanation: 'A Large Language Model is a neural network trained on billions of words from the internet, books, and code. During training it learns statistical patterns in language — which words follow which — until it can produce text that is coherent, contextually relevant, and often indistinguishable from human writing.\n\nLLMs do not "know" facts the way a database does. They generate responses by predicting the most statistically likely continuation of a given input. This is why they can be confidently wrong — a phenomenon called hallucination.',
    example: 'ChatGPT, Claude, and Gemini are all powered by LLMs. When you ask "Write a marketing email for my product," the LLM generates that email by predicting token by token what a good marketing email looks like.',
    why_it_matters: 'LLMs are the foundation of nearly every AI tool you use today. Understanding what they are — and critically, what they are not — helps you use them more effectively and avoid common pitfalls like trusting hallucinated facts.',
    where_its_used: 'Every AI chatbot, coding assistant, and writing tool. Also used internally in automation pipelines, RAG systems, and AI agents.',
    related_tool_slugs: ['chatgpt', 'claude', 'gemini'],
    related_skill_slugs: ['prompt-engineering-basics'],
    related_term_slugs: ['token', 'context-window', 'hallucination', 'prompt-engineering'],
    status: 'published',
    published_at: '2026-05-15T00:00:00Z',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
  {
    id: 'g-002',
    title: 'Hallucination',
    slug: 'hallucination',
    simple_definition: 'When an AI model confidently states something that is false or made up.',
    full_explanation: 'Hallucination happens because LLMs generate text by predicting the most statistically likely next token — they are not retrieving verified facts from a database. When they lack reliable training data for a query, they may fabricate plausible-sounding answers.\n\nCommon hallucinations include: invented citations, wrong dates, non-existent products, and incorrect technical specifications. The danger is that the model states these with the same confident tone as accurate information.',
    example: 'You ask: "What did CEO Jane Smith say about the merger?" The LLM may generate a convincing quote that Jane Smith never actually said.',
    why_it_matters: 'If you use AI outputs without verification — especially for facts, citations, or technical details — you risk sharing or acting on false information. The fix: treat AI outputs as a draft to be verified, not a source of truth.',
    where_its_used: 'All LLM-based tools. Particularly risky in research, legal, medical, or financial contexts. Reduced (but not eliminated) by grounding techniques like RAG.',
    related_tool_slugs: ['perplexity', 'chatgpt'],
    related_skill_slugs: ['prompt-engineering-basics', 'perplexity-deep-research'],
    related_term_slugs: ['llm', 'rag', 'grounding'],
    status: 'published',
    published_at: '2026-05-15T00:00:00Z',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
  {
    id: 'g-003',
    title: 'RAG (Retrieval-Augmented Generation)',
    slug: 'rag',
    simple_definition: 'A technique that gives an AI model access to a private knowledge base so it can answer questions based on your specific documents.',
    full_explanation: 'RAG solves a fundamental limitation of LLMs: they only know what was in their training data. With RAG, when you ask a question, the system first searches a database of your documents (using vector search), retrieves the most relevant passages, and feeds those passages into the LLM prompt as context. The LLM then generates an answer grounded in those retrieved passages.\n\nThis is how enterprise chatbots answer questions about internal documentation, how Perplexity answers with citations, and how tools like NotebookLM let you "chat with a PDF."',
    example: 'You upload 500 pages of company policy documents. When an employee asks "What is the vacation policy for remote workers?", the RAG system retrieves the relevant policy section and the LLM summarizes it accurately.',
    why_it_matters: 'RAG lets you build AI tools that know your specific business context without expensive fine-tuning. It also reduces hallucinations by grounding answers in retrieved facts.',
    where_its_used: 'Enterprise chatbots, internal knowledge bases, document Q&A tools, customer support automation.',
    related_tool_slugs: ['notebooklm', 'perplexity'],
    related_skill_slugs: ['build-rag-system', 'build-first-ai-agent'],
    related_term_slugs: ['embeddings', 'vector-database', 'llm', 'grounding'],
    status: 'published',
    published_at: '2026-05-15T00:00:00Z',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
  {
    id: 'g-004',
    title: 'Prompt Engineering',
    slug: 'prompt-engineering',
    simple_definition: 'The skill of writing instructions that get AI models to produce better, more consistent results.',
    full_explanation: 'Prompt engineering is the practice of crafting inputs to AI models strategically. A well-engineered prompt specifies the role the AI should play, the exact task, relevant context, constraints, and the desired output format. Small changes in how you phrase a prompt can dramatically change the quality and consistency of outputs.',
    example: 'Bad prompt: "Write something about marketing." Better prompt: "You are a B2B SaaS marketing expert. Write a 150-word LinkedIn post for a founder announcing a new product feature. Tone: confident but not salesy. Include one specific statistic about user adoption."',
    why_it_matters: 'Prompt engineering is the single highest-ROI AI skill for most people. You do not need to understand how models work — just how to communicate with them effectively.',
    where_its_used: 'Any AI tool that accepts text input. Critical for consistent output quality in automation pipelines and agent systems.',
    related_tool_slugs: ['chatgpt', 'claude'],
    related_skill_slugs: ['prompt-engineering-basics', 'write-system-prompts'],
    related_term_slugs: ['system-prompt', 'llm', 'token', 'chain-of-thought'],
    status: 'published',
    published_at: '2026-05-15T00:00:00Z',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
  {
    id: 'g-005',
    title: 'Token',
    slug: 'token',
    simple_definition: 'The basic unit of text that AI models process — roughly 3/4 of a word on average.',
    full_explanation: 'LLMs do not process text character by character or word by word — they process tokens. A token is a chunk of text determined during training, typically 3-4 characters long. "ChatGPT" is 2 tokens. "Hello world" is 2 tokens. A 1,000-word document is roughly 750 tokens.\n\nTokens matter because models have a context window limit measured in tokens, and API costs are priced per token. Understanding tokens helps you optimize both what you can fit in a single prompt and what it costs to run.',
    example: 'GPT-4o has a 128K token context window — that is roughly 96,000 words or about 300 pages of text you can send in a single request.',
    why_it_matters: 'Token limits define how much you can give to an AI at once. API pricing is per token. Knowing this helps you write efficient prompts and avoid hitting limits.',
    where_its_used: 'Every LLM API. Critical for understanding pricing, context window limits, and why long conversations eventually "forget" earlier content.',
    related_tool_slugs: ['chatgpt', 'claude'],
    related_skill_slugs: ['prompt-engineering-basics'],
    related_term_slugs: ['context-window', 'llm', 'inference'],
    status: 'published',
    published_at: '2026-05-15T00:00:00Z',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
]
