import type { Tool } from '@/types/tool'

export const MOCK_TOOLS: Tool[] = [
  {
    id: '1',
    title: 'ChatGPT',
    slug: 'chatgpt',
    short_description: 'OpenAI\'s flagship conversational AI for writing, coding, research, and problem-solving.',
    long_description: 'ChatGPT is a large language model built by OpenAI. It can write, edit, summarize, translate, debug code, answer questions, and assist with complex reasoning tasks across virtually any domain.',
    website_url: 'https://chat.openai.com',
    category_name: 'AI Assistant',
    category_id: 'ai-assistant',
    tags: ['writing', 'coding', 'research', 'chatbot'],
    use_cases: ['content-writing', 'code-generation', 'research', 'customer-support'],
    best_for: ['Writing', 'Coding', 'Research', 'Brainstorming'],
    not_ideal_for: ['Real-time data', 'Image generation'],
    user_types: ['creator', 'developer', 'business', 'beginner'],
    avelix_rating: 4.8,
    avelix_recommendation: 'Best all-around AI assistant for most users.',
    pricing_model: 'freemium',
    has_free_plan: true,
    pricing_summary: 'Free tier with GPT-3.5. ChatGPT Plus at $20/mo for GPT-4.',
    has_api: true,
    is_no_code: true,
    platforms: ['web', 'ios', 'android'],
    integrations: ['Zapier', 'Make', 'Slack'],
    has_arabic_support: true,
    related_tool_slugs: ['claude', 'gemini'],
    related_model_slugs: ['gpt-4o'],
    related_skill_slugs: ['prompt-engineering'],
    pros: ['Best general-purpose LLM', 'Huge ecosystem', 'Free tier available', 'Excellent coding support'],
    cons: ['Knowledge cutoff', 'Can hallucinate', 'Plus plan required for GPT-4'],
    main_features: ['Natural language chat', 'Code interpreter', 'Image generation (DALL·E)', 'File uploads', 'Custom GPTs'],
    example_prompts: ['Write a product description for [product]', 'Debug this code: [code]', 'Summarize this article: [text]'],
    screenshots: [],
    status: 'published',
    source_urls: ['https://openai.com/chatgpt'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-01-01T00:00:00Z',
    confidence_score: 0.97,
    ai_generated: false,
  },
  {
    id: '2',
    title: 'Claude',
    slug: 'claude',
    short_description: 'Anthropic\'s AI assistant known for nuanced reasoning, long-context analysis, and safe outputs.',
    long_description: 'Claude is a large language model by Anthropic, built with a focus on safety and helpfulness. It excels at long-document analysis, nuanced writing, coding, and complex reasoning.',
    website_url: 'https://claude.ai',
    category_name: 'AI Assistant',
    category_id: 'ai-assistant',
    tags: ['writing', 'analysis', 'coding', 'research'],
    use_cases: ['content-writing', 'document-analysis', 'code-generation', 'research'],
    best_for: ['Long-document analysis', 'Nuanced writing', 'Code review'],
    not_ideal_for: ['Image generation', 'Real-time data'],
    user_types: ['developer', 'business', 'creator'],
    avelix_rating: 4.7,
    avelix_recommendation: 'Best for long-context tasks and nuanced reasoning.',
    pricing_model: 'freemium',
    has_free_plan: true,
    pricing_summary: 'Free tier. Claude Pro at $20/mo.',
    has_api: true,
    is_no_code: true,
    platforms: ['web', 'ios', 'android'],
    integrations: ['API', 'Slack'],
    has_arabic_support: false,
    related_tool_slugs: ['chatgpt', 'gemini'],
    related_model_slugs: ['claude-3-5-sonnet'],
    related_skill_slugs: ['prompt-engineering'],
    pros: ['200K context window', 'Strong safety', 'Excellent at nuanced tasks', 'Great for coding'],
    cons: ['No image generation', 'Slower than GPT-4o for simple tasks'],
    main_features: ['200K context window', 'Document upload', 'Code generation', 'Projects', 'Artifact viewer'],
    example_prompts: ['Analyze this 50-page PDF: [file]', 'Review this code for bugs: [code]'],
    screenshots: [],
    status: 'published',
    source_urls: ['https://anthropic.com/claude'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-01-01T00:00:00Z',
    confidence_score: 0.96,
    ai_generated: false,
  },
  {
    id: '3',
    title: 'Midjourney',
    slug: 'midjourney',
    short_description: 'The leading AI image generation tool for stunning, artistic visuals via Discord or web.',
    long_description: 'Midjourney is an AI image generator that creates high-quality, artistic images from text prompts. It is known for its distinctive aesthetic quality and is widely used by designers, marketers, and creators.',
    website_url: 'https://midjourney.com',
    category_name: 'Image Generation',
    category_id: 'image-generation',
    tags: ['images', 'design', 'art', 'creative'],
    use_cases: ['image-generation', 'marketing-visuals', 'concept-art'],
    best_for: ['Art', 'Marketing visuals', 'Concept design', 'Social media content'],
    not_ideal_for: ['Exact text in images', 'Photorealistic product photos'],
    user_types: ['creator', 'business'],
    avelix_rating: 4.6,
    avelix_recommendation: 'Best for artistic image generation.',
    pricing_model: 'paid',
    has_free_plan: false,
    pricing_summary: 'Basic plan at $10/mo. Standard at $30/mo.',
    has_api: false,
    is_no_code: true,
    platforms: ['web'],
    integrations: ['Discord'],
    has_arabic_support: false,
    related_tool_slugs: ['dall-e', 'stable-diffusion'],
    related_model_slugs: [],
    related_skill_slugs: ['prompt-engineering', 'image-prompting'],
    pros: ['Highest artistic quality', 'Active community', 'Consistent style'],
    cons: ['Paid only', 'No free tier', 'Limited control over exact details'],
    main_features: ['Text-to-image', 'Image variations', 'Upscaling', 'Style references', 'Web editor'],
    example_prompts: ['A futuristic city at night, neon lights, cinematic --ar 16:9 --v 6'],
    screenshots: [],
    status: 'published',
    source_urls: ['https://midjourney.com'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-01-01T00:00:00Z',
    confidence_score: 0.95,
    ai_generated: false,
  },
  {
    id: '4',
    title: 'Cursor',
    slug: 'cursor',
    short_description: 'AI-powered code editor built for developers. Write, edit, and debug code with AI inline.',
    long_description: 'Cursor is a fork of VS Code with deep AI integration. It allows developers to chat with their codebase, generate code from natural language, and auto-fix bugs — all within the editor.',
    website_url: 'https://cursor.com',
    category_name: 'AI Coding',
    category_id: 'ai-coding',
    tags: ['coding', 'developer-tools', 'ide', 'automation'],
    use_cases: ['code-generation', 'debugging', 'refactoring'],
    best_for: ['Full-stack development', 'Code refactoring', 'Debugging'],
    not_ideal_for: ['Non-developers', 'Simple scripts'],
    user_types: ['developer'],
    avelix_rating: 4.7,
    avelix_recommendation: 'Best AI coding tool for professional developers.',
    pricing_model: 'freemium',
    has_free_plan: true,
    pricing_summary: 'Free tier. Pro at $20/mo. Business at $40/mo.',
    has_api: false,
    is_no_code: false,
    platforms: ['desktop'],
    integrations: ['GitHub', 'GitLab', 'VS Code extensions'],
    has_arabic_support: false,
    related_tool_slugs: ['chatgpt', 'github-copilot'],
    related_model_slugs: ['claude-3-5-sonnet', 'gpt-4o'],
    related_skill_slugs: ['prompt-engineering', 'ai-coding'],
    pros: ['Full codebase context', 'Multiple AI models', 'VS Code compatible', 'Fast iteration'],
    cons: ['Requires technical setup', 'Monthly cost for heavy use'],
    main_features: ['Chat with codebase', 'Inline code generation', 'Auto-fix', 'Multi-file edits', 'Agent mode'],
    example_prompts: ['Refactor this function to use async/await', 'Add error handling to this API route'],
    screenshots: [],
    status: 'published',
    source_urls: ['https://cursor.com'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-01-01T00:00:00Z',
    confidence_score: 0.95,
    ai_generated: false,
  },
  {
    id: '5',
    title: 'ElevenLabs',
    slug: 'elevenlabs',
    short_description: 'AI voice cloning and text-to-speech platform with ultra-realistic voices.',
    long_description: 'ElevenLabs offers state-of-the-art AI voice synthesis and cloning. Create custom voices, generate natural speech in 29 languages, and build audio products at scale.',
    website_url: 'https://elevenlabs.io',
    category_name: 'AI Voice',
    category_id: 'ai-voice',
    tags: ['voice', 'audio', 'tts', 'cloning'],
    use_cases: ['voiceover', 'audiobooks', 'podcasts', 'customer-support'],
    best_for: ['Voiceovers', 'Audiobooks', 'Podcast production', 'Video dubbing'],
    not_ideal_for: ['Real-time phone calls (high latency)'],
    user_types: ['creator', 'business'],
    avelix_rating: 4.8,
    avelix_recommendation: 'Best AI voice tool — unmatched realism.',
    pricing_model: 'freemium',
    has_free_plan: true,
    pricing_summary: 'Free: 10K chars/mo. Starter $5/mo. Creator $22/mo.',
    has_api: true,
    is_no_code: true,
    platforms: ['web'],
    integrations: ['API', 'Zapier', 'Make'],
    has_arabic_support: true,
    related_tool_slugs: ['heygen', 'descript'],
    related_model_slugs: [],
    related_skill_slugs: ['ai-voice', 'content-creation'],
    pros: ['Most realistic voices', 'Voice cloning', '29 languages', 'Strong API'],
    cons: ['Free tier limited', 'Voice cloning requires consent'],
    main_features: ['Voice cloning', 'Text-to-speech', '29 languages', 'Voice design', 'Dubbing'],
    example_prompts: [],
    screenshots: [],
    status: 'published',
    source_urls: ['https://elevenlabs.io'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-01-01T00:00:00Z',
    confidence_score: 0.95,
    ai_generated: false,
  },
  {
    id: '6',
    title: 'n8n',
    slug: 'n8n',
    short_description: 'Open-source workflow automation platform. Connect any tool, automate any process.',
    long_description: 'n8n is a powerful, self-hostable workflow automation tool with 400+ integrations. It allows non-developers and developers alike to automate business processes, data pipelines, and AI workflows without writing code.',
    website_url: 'https://n8n.io',
    category_name: 'Automation',
    category_id: 'automation',
    tags: ['automation', 'workflow', 'no-code', 'integration'],
    use_cases: ['workflow-automation', 'data-pipeline', 'ai-agent', 'business-automation'],
    best_for: ['Business automation', 'AI pipelines', 'Data sync', 'Webhook workflows'],
    not_ideal_for: ['Simple one-step automations (use Zapier)'],
    user_types: ['developer', 'business'],
    avelix_rating: 4.6,
    avelix_recommendation: 'Best automation tool for technical teams and AI builders.',
    pricing_model: 'open-source',
    has_free_plan: true,
    pricing_summary: 'Self-hosted: free forever. Cloud: from $20/mo.',
    has_api: true,
    is_no_code: true,
    platforms: ['web', 'desktop'],
    integrations: ['400+ apps', 'OpenAI', 'Supabase', 'Slack', 'Gmail'],
    has_arabic_support: false,
    related_tool_slugs: ['zapier', 'make'],
    related_model_slugs: [],
    related_skill_slugs: ['workflow-automation', 'ai-agents'],
    pros: ['Open source & self-hostable', '400+ integrations', 'AI workflow native', 'Code nodes available'],
    cons: ['Steeper learning curve', 'Self-hosting requires DevOps'],
    main_features: ['Visual workflow builder', '400+ integrations', 'AI nodes', 'Self-hosting', 'Code nodes'],
    example_prompts: [],
    screenshots: [],
    status: 'published',
    source_urls: ['https://n8n.io'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-01-01T00:00:00Z',
    confidence_score: 0.94,
    ai_generated: false,
  },
  {
    id: '7',
    title: 'Perplexity AI',
    slug: 'perplexity-ai',
    short_description: 'AI search engine that answers questions with cited, real-time web sources.',
    long_description: 'Perplexity AI is a conversational search engine that combines large language models with real-time web search. Every answer includes cited sources, making it ideal for research.',
    website_url: 'https://perplexity.ai',
    category_name: 'AI Research',
    category_id: 'ai-research',
    tags: ['research', 'search', 'citations', 'real-time'],
    use_cases: ['research', 'fact-checking', 'market-research'],
    best_for: ['Research', 'Real-time information', 'Fact-checking with sources'],
    not_ideal_for: ['Creative writing', 'Code generation'],
    user_types: ['creator', 'business', 'beginner'],
    avelix_rating: 4.5,
    avelix_recommendation: 'Best AI search tool — replaces Google for research.',
    pricing_model: 'freemium',
    has_free_plan: true,
    pricing_summary: 'Free with limited Pro queries. Pro at $20/mo.',
    has_api: true,
    is_no_code: true,
    platforms: ['web', 'ios', 'android'],
    integrations: ['API'],
    has_arabic_support: false,
    related_tool_slugs: ['chatgpt', 'claude'],
    related_model_slugs: [],
    related_skill_slugs: ['research', 'prompt-engineering'],
    pros: ['Real-time web access', 'Cited sources', 'Free tier generous', 'Great for research'],
    cons: ['Not for creative tasks', 'Can be verbose'],
    main_features: ['Real-time web search', 'Cited answers', 'Pro search', 'Collections', 'API'],
    example_prompts: ['What are the latest AI tools launched in 2025?'],
    screenshots: [],
    status: 'published',
    source_urls: ['https://perplexity.ai'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-01-01T00:00:00Z',
    confidence_score: 0.93,
    ai_generated: false,
  },
  {
    id: '8',
    title: 'Gemini',
    slug: 'gemini',
    short_description: 'Google\'s multimodal AI assistant integrated across Google Workspace and Android.',
    long_description: 'Gemini is Google\'s flagship AI assistant, built natively into Google Search, Docs, Gmail, and Android. It handles text, images, code, and audio with deep Google ecosystem integration.',
    website_url: 'https://gemini.google.com',
    category_name: 'AI Assistant',
    category_id: 'ai-assistant',
    tags: ['multimodal', 'google', 'workspace', 'coding'],
    use_cases: ['content-writing', 'research', 'google-workspace', 'code-generation'],
    best_for: ['Google Workspace users', 'Multimodal tasks', 'Research with Google integration'],
    not_ideal_for: ['Complex coding', 'Long-document analysis'],
    user_types: ['creator', 'business', 'beginner'],
    avelix_rating: 4.4,
    avelix_recommendation: 'Best for users in the Google ecosystem.',
    pricing_model: 'freemium',
    has_free_plan: true,
    pricing_summary: 'Free with Gemini 1.5 Flash. Advanced at $19.99/mo.',
    has_api: true,
    is_no_code: true,
    platforms: ['web', 'ios', 'android'],
    integrations: ['Google Docs', 'Gmail', 'Google Search', 'YouTube'],
    has_arabic_support: true,
    related_tool_slugs: ['chatgpt', 'claude'],
    related_model_slugs: ['gemini-1-5-pro'],
    related_skill_slugs: ['prompt-engineering'],
    pros: ['Google integration', 'Free tier', 'Multimodal', 'Long context'],
    cons: ['Behind GPT-4 for coding', 'Google data policy concerns'],
    main_features: ['Multimodal input', 'Google Workspace integration', 'Code generation', '1M token context', 'Deep Research'],
    example_prompts: ['Summarize my last 10 emails', 'Write a Google Docs report on [topic]'],
    screenshots: [],
    status: 'published',
    source_urls: ['https://gemini.google.com'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    last_reviewed_at: '2025-05-01T00:00:00Z',
    published_at: '2024-01-01T00:00:00Z',
    confidence_score: 0.93,
    ai_generated: false,
  },
]

export const CATEGORIES = [
  { id: 'ai-assistant', name: 'AI Assistant', icon: 'smart_toy' },
  { id: 'image-generation', name: 'Image Generation', icon: 'image' },
  { id: 'ai-coding', name: 'AI Coding', icon: 'code' },
  { id: 'ai-voice', name: 'AI Voice', icon: 'mic' },
  { id: 'automation', name: 'Automation', icon: 'webhook' },
  { id: 'ai-research', name: 'AI Research', icon: 'query_stats' },
  { id: 'ai-writing', name: 'AI Writing', icon: 'edit_note' },
  { id: 'ai-video', name: 'AI Video', icon: 'movie' },
]
